# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_root:
    resource: "@MinecrafterdkSiteBundle/Controller/SiteController.php"
    type:     annotation

servers:
    pattern:  /servers
    defaults: { _controller: MinecrafterdkSiteBundle:Servers:list }