_site:
    resource: "@MinecrafterdkSiteBundle/Controller/SiteController.php"
    type: annotation

minecrafterdk_site_user_new:
    pattern: /opret_bruger
    defaults: { _controller: MinecrafterdkSiteBundle:User:new }

minecrafterdk_site_server_index:
    pattern: /servere
    defaults: { _controller: MinecrafterdkSiteBundle:Server:index }

minecrafterdk_site_server_view:
    pattern: /server/{slug}
    defaults: { _controller: MinecrafterdkSiteBundle:Server:view }
